export const northWindTraders = [
    'General',
    'Marketing',
    'Overview',
    'Performance',
    'Shiproom',
    'Telemetry',
    'Sales',
    'Finance',
    'Human Resources',
    'Inventory',
    'Purchasing',
    'Shipping',
    'Customer Service',
    'Product Development',
    'Quality Assurance',
    'Research and Development',
    'Information Technology',
    'Operations',
    'Supply Chain',
    'Logistics',
    'Vendor Management',
    'Business Development',
    'Accounting',
    'Legal',
    'Risk Management',
    'Facilities Management',
    'Training and Development',
    'Internal Audit',
    'Public Relations',
    'Safety and Security',
    'Corporate Communications',
    'Strategic Planning',
    'Business Analysis',
    'Consulting',
  ];

export const tailspinTraders = [
    'Safety and Security',
    'Corporate Communications',
    'Strategic Planning',
    'Business Analysis',
    'Consulting',
]
export const accountTeams = [
  'General',
  'Accounting',
  'Finance',
  'Fiscal Year Planning',
  'Strategy',
  'Safety and Security',
  'Corporate Communications',
  'Strategic Planning',
  'Business Analysis',
  'Consulting',
]
  